---
- name: Create odoo user
  postgresql_user: 
    state: present
    login_user: postgres
    role_attr_flags: "SUPERUSER,CREATEDB"
    name: "{{ item }}" 
  with_items:
    - odoo
    - root  

- name: create group "odoo" 
  group:
    name: odoo  
    state: present

- name: creating a new user “odoo” and provide a home directory     
  user:
    name: odoo
    group: odoo
    home: /opt/odoo

- name: Unpacks gdata-2.0.18.tar.gz in op/odoo after copying it from the local machine
  unarchive:
    src: /home/abderrahim/Desktop/ansible-test/gdata-2.0.18.tar.gz #your local path to gdata-2.0.18.tar.gz
    dest: /opt/odoo    
    remote_src: no
    owner: odoo 
    mode : 01777

   

- name: runs the setup.py through a shell 
  shell: python setup.py install
  args:
    chdir: /opt/odoo/gdata-2.0.18

       
    
- name: get Odoo from git
  become_user: odoo 
  become_method: su 
  become_flags: '-s /bin/bash'
  git: 
    repo: https://github.com/odoo/odoo.git
    dest: /opt/odoo/odoo 
    version: 10.0
    depth: 1 


- name: create oddo directory in /var/log
  file: 
    path: /var/log/odoo 
    state: directory
    owner: odoo
    group: root

- name: create a odoo.conf file and add into some configuration
  copy:
    content: '[options]

; This is the password that allows database operations:

; admin_passwd = PASSWORD

db_host = False

db_port = False

db_user = odoo

db_password = False

addons_path = /opt/odoo/odoo-10.0/addons

;Log Settings

logfile = /var/log/odoo/odoo.log

log_level = error

#######'
    dest: /etc/odoo.conf
    force: no
    group: root
    owner: root


- name : download wkhtmltopdf package 
  get_url:
    url: https://builds.wkhtmltopdf.org/0.12.1.3/wkhtmltox_0.12.1.3-1~bionic_amd64.deb
    dest: /opt/odoo

- name: Install wkhtmltopdf
  apt:
    deb: /opt/odoo/wkhtmltox_0.12.1.3-1~bionic_amd64.deb    
    

#- name : start odoo server
#  command: ./odoo-bin
#  args:
#    chdir: /opt/odoo/odoo 


...
